In [1]:
import torch
import numpy as np
import torch.nn as nn
import os
import pandas as pd
from torch.autograd import Variable

In [2]:
x_data=Variable(torch.Tensor([[2],[4],[6],[8],[10],[12]]))
y_data=Variable(torch.Tensor([[1],[3],[5],[7],[9],[11]]))
print("x and y are 5 by 1 matrices")
print(x_data)
print(y_data)

x and y are 5 by 1 matrices
tensor([[ 2.],
        [ 4.],
        [ 6.],
        [ 8.],
        [10.],
        [12.]])
tensor([[ 1.],
        [ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.]])


In [3]:
x_data.shape

torch.Size([6, 1])

In [4]:
x_data.size()

torch.Size([6, 1])

In [5]:
y_data.shape

torch.Size([6, 1])

In [6]:
class Model(nn.Module):
    def __init__(self):
        super(Model,self).__init__()
        #self.linear=nn.Linear(input_dim,output_dim)
        self.linear=nn.Linear(1,1)# 1 in and 1 out
        
    def forward(self,x):
        y_pred=self.linear(x)
        return y_pred
        
        
model=Model()
'''
class torch.nn.MSELoss(size_average=True)
Creates a criterion that measures the mean squared error between n elements in the input x and target y:
'''
loss_function=nn.MSELoss(size_average=False)
#  stochastic gradient descent with a leaning rate (lr) of 0.05
optimizer=torch.optim.SGD(model.parameters(),lr=0.001,momentum=0.9)
for eporch in range(50):
    # predicting y
    y_pred=model(x_data)
    # computing the loss
    loss=loss_function(y_pred,y_data)
    print('epoch \n',eporch,'  y_values \n',y_data,'y_pred\n',y_pred,' ','loss \n',loss.data)
    # Zero gradients, perform a backward pass, and update the weights.
    
    # zero the gradients
    optimizer.zero_grad()
    #perform backward-propagation
    loss.backward()
    # All optimizers implement a step() method, that updates the parameters. It can be used as:
    #optimizer.step()
    optimizer.step()
    
#[w,b]=model.parameters
#def get_para():
 #   return w.data[0][0], b.data[0]

hour_four=Variable(torch.Tensor([[4.0]]))   

print('after training',4,model.forward(hour_four).data[0][0])

C:\Anaconda3\lib\site-packages\torch\nn\_reduction.py:46: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))


epoch 
 0   y_values 
 tensor([[ 1.],
        [ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.]]) y_pred
 tensor([[0.1606],
        [1.2063],
        [2.2520],
        [3.2977],
        [4.3433],
        [5.3890]], grad_fn=<AddmmBackward>)   loss 
 tensor(78.3488)
epoch 
 1   y_values 
 tensor([[ 1.],
        [ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.]]) y_pred
 tensor([[0.8748],
        [2.5959],
        [4.3170],
        [6.0381],
        [7.7592],
        [9.4803]], grad_fn=<AddmmBackward>)   loss 
 tensor(5.4197)
epoch 
 2   y_values 
 tensor([[ 1.],
        [ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.]]) y_pred
 tensor([[ 1.7046],
        [ 4.2108],
        [ 6.7170],
        [ 9.2232],
        [11.7295],
        [14.2357]], grad_fn=<AddmmBackward>)   loss 
 tensor(27.7731)
epoch 
 3   y_values 
 tensor([[ 1.],
        [ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.]]) y_pred
 tensor([[ 2.0259],
        [ 4

        [9.9907]], grad_fn=<AddmmBackward>)   loss 
 tensor(2.4055)
epoch 
 29   y_values 
 tensor([[ 1.],
        [ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.]]) y_pred
 tensor([[ 1.1066],
        [ 3.1118],
        [ 5.1171],
        [ 7.1223],
        [ 9.1275],
        [11.1328]], grad_fn=<AddmmBackward>)   loss 
 tensor(0.0864)
epoch 
 30   y_values 
 tensor([[ 1.],
        [ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.]]) y_pred
 tensor([[ 1.2618],
        [ 3.4163],
        [ 5.5707],
        [ 7.7252],
        [ 9.8797],
        [12.0342]], grad_fn=<AddmmBackward>)   loss 
 tensor(2.9369)
epoch 
 31   y_values 
 tensor([[ 1.],
        [ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.]]) y_pred
 tensor([[ 1.2632],
        [ 3.4215],
        [ 5.5798],
        [ 7.7381],
        [ 9.8964],
        [12.0547]], grad_fn=<AddmmBackward>)   loss 
 tensor(3.0440)
epoch 
 32   y_values 
 tensor([[ 1.],
        [ 3.],
        [ 5.],
  

In [7]:
# a function to load the data
def load_data(path='data'):
    data=os.path.join(path,'Lemonade.csv')
    return pd.read_csv(data)
    

In [8]:

#data=pd.read_csv('Lemonade.csv')
data=load_data()

In [9]:
data.head(3)

Date      Day  Temperature  Rainfall  Flyers  Price  Sales
0  01/01/2017   Sunday         27.0      2.00      15    0.3     10
1  02/01/2017   Monday         28.9      1.33      15    0.3     13
2  03/01/2017  Tuesday         34.5      1.33      27    0.3     15

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 7 columns):
Date           365 non-null object
Day            365 non-null object
Temperature    365 non-null float64
Rainfall       365 non-null float64
Flyers         365 non-null int64
Price          365 non-null float64
Sales          365 non-null int64
dtypes: float64(3), int64(2), object(2)
memory usage: 20.0+ KB


In [11]:
# checking for the number of missing values within the data
#from the result the data does not contain missing values
data.isnull().sum()

Date           0
Day            0
Temperature    0
Rainfall       0
Flyers         0
Price          0
Sales          0
dtype: int64

In [12]:
# dropping the date and day column since we do not need them
data.drop(['Date','Day'],axis=1,inplace=True)

In [13]:
data.head(4)

Temperature  Rainfall  Flyers  Price  Sales
0         27.0      2.00      15    0.3     10
1         28.9      1.33      15    0.3     13
2         34.5      1.33      27    0.3     15
3         44.1      1.05      28    0.3     17

In [17]:
x_train_data=data.loc[:,['Temperature','Rainfall','Flyers','Price']]
y_train_data=data.loc[:,'Sales']

In [18]:
#y=torch.Tensor(y_train_data)
#y_train_data=np.array(y_train_data)
x=np.array(x_train_data)
y=np.array(y_train_data)
y=torch.from_numpy(y)
x=torch.from_numpy(x)

In [19]:
x=Variable(x)
y=y.reshape(-1,1)
y=Variable(y)

In [21]:
class L_regression(nn.Module):
    def __init__(self,n_features):
        super(L_regression,self).__init__()
        #self.linear=nn.Linear(input_dim,output_dim)
        self.linear=nn.Linear(in_features=n_features,out_features=1,bias=True)
        
    def forward(self,x_in):
        return self.linear(x_in)
        
l_reg=L_regression(n_features=4)
'''
class torch.nn.MSELoss(size_average=True)
Creates a criterion that measures the mean squared error between n elements in the input x and target y:
'''
loss_fu=nn.MSELoss()
#  stochastic gradient descent with a leaning rate (lr) of 0.05
#opt=torch.optim.SGD(l_reg.parameters(),lr=0.01,momentum=0.7)
opt=torch.optim.Adam(l_reg.parameters(),lr=0.01,weight_decay=1e-5)


for eporch in range(100):
    # predicting y
    y_pred=l_reg(x.float())
    # computing the loss
    loss=loss_fu(y_pred,y.float())
    print('epoch \n',eporch,'\n loss \n',loss.data)
    # Zero gradients, perform a backward pass, and update the weights.
    
    # zero the gradients
    opt.zero_grad()
    #perform backward-propagation
    loss.backward()
    # All optimizers implement a step() method, that updates the parameters. It can be used as:
    #optimizer.step()
    opt.step()

epoch 
 0 
 loss 
 tensor(1706.7155)
epoch 
 1 
 loss 
 tensor(1620.4502)
epoch 
 2 
 loss 
 tensor(1536.5309)
epoch 
 3 
 loss 
 tensor(1454.9963)
epoch 
 4 
 loss 
 tensor(1375.8818)
epoch 
 5 
 loss 
 tensor(1299.2189)
epoch 
 6 
 loss 
 tensor(1225.0354)
epoch 
 7 
 loss 
 tensor(1153.3549)
epoch 
 8 
 loss 
 tensor(1084.1964)
epoch 
 9 
 loss 
 tensor(1017.5747)
epoch 
 10 
 loss 
 tensor(953.4995)
epoch 
 11 
 loss 
 tensor(891.9758)
epoch 
 12 
 loss 
 tensor(833.0032)
epoch 
 13 
 loss 
 tensor(776.5765)
epoch 
 14 
 loss 
 tensor(722.6852)
epoch 
 15 
 loss 
 tensor(671.3132)
epoch 
 16 
 loss 
 tensor(622.4391)
epoch 
 17 
 loss 
 tensor(576.0366)
epoch 
 18 
 loss 
 tensor(532.0736)
epoch 
 19 
 loss 
 tensor(490.5130)
epoch 
 20 
 loss 
 tensor(451.3127)
epoch 
 21 
 loss 
 tensor(414.4255)
epoch 
 22 
 loss 
 tensor(379.7997)
epoch 
 23 
 loss 
 tensor(347.3789)
epoch 
 24 
 loss 
 tensor(317.1025)
epoch 
 25 
 loss 
 tensor(288.9059)
epoch 
 26 
 loss 
 tensor(262.7208)
e