<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Convolution-Operation" data-toc-modified-id="Convolution-Operation-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Convolution Operation</a></span></li><li><span><a href="#Discrete-Convolution" data-toc-modified-id="Discrete-Convolution-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Discrete Convolution</a></span></li><li><span><a href="#CROSS-CORRELATION-OPERATIONS" data-toc-modified-id="CROSS-CORRELATION-OPERATIONS-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>CROSS-CORRELATION OPERATIONS</a></span></li><li><span><a href="#Constraining-the-MLP" data-toc-modified-id="Constraining-the-MLP-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Constraining the MLP</a></span></li><li><span><a href="#Translation-Invariance" data-toc-modified-id="Translation-Invariance-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Translation Invariance</a></span></li><li><span><a href="#Convolutional-Layers" data-toc-modified-id="Convolutional-Layers-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Convolutional Layers</a></span></li><li><span><a href="#Object-Edge-Detection-in-Images" data-toc-modified-id="Object-Edge-Detection-in-Images-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Object Edge Detection in Images</a></span></li><li><span><a href="#Learning-a-Kernel" data-toc-modified-id="Learning-a-Kernel-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Learning a Kernel</a></span></li><li><span><a href="#Padding" data-toc-modified-id="Padding-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Padding</a></span></li><li><span><a href="#Stride" data-toc-modified-id="Stride-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Stride</a></span></li><li><span><a href="#POOLING" data-toc-modified-id="POOLING-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>POOLING</a></span></li></ul></div>

## Convolution Operation
In its most general form convolution is a mathematical operator which takes two functions f and g and produces a third function s. It is the overlap of f and g as g is shifted over f and is defined as
$$ s(t)=(f*g)(n)=\int_{-\infty}^{\infty}f(m)g(n-m)dm $$

In convolutional network terminology, the first argument f to the convolution is often referred to as the input and the second argument g as the kernel. The output is sometimes referred to as the feature map.

Convolution is commutative  so it can be written as

$$ s(t)=(f*g)(n)=\int_{-\infty}^{\infty}f(n-m)g(m)dm $$
## Discrete Convolution
If we assume that f and g are defined only on integer n then we can define the discrete convolution as
$$ s(t)=(f*g)(n)=\sum_{m=-\infty}^{\infty}f(m)g(n-m) $$


If we use a two-dimensional image $I$ as our input, and probably a two-dimensional kernel (known as the convolution kernel, a filter, or simply the layerʼs weights that are often learnable parameters) $K$ of size $m \times n$ . The image $I$ is convolved with the filter $K$ and produces the <b>feature map (channels) S</b>. The convolution operation is denoted by I*K and is mathematically given as
$$ S(i,j)=(I \times K)(i,j)=\sum_{m}\sum_{n}I(m,n)K(i-m,j-n)=\sum_{m}\sum_{n}I(i-m,j-n) K(m,n) $$ 

where $I(i,j)$  denote the pixel at location (i, j) in the input image



----
<cite style='color:blue'> The commutative property of convolution arises because we have flipped the kernel relative to the input, in the sense that as m increases, the index into the input increases, but the index into the kernel decreases. The only reason to flip the kernel is to obtain the commutative property. While the commutative property is useful for writing proofs, it is not usually an important property of a neural
network implementation. <kbd>Instead, many neural network libraries implement a related function called the cross-correlation, which is the same as convolution but without flipping the kernel. Many machine learning libraries implement cross-correlation but call it convolution</kbd></cite>

<p>(source: Deep Learning by Ian Goodfellow,Yoshua Bengio and Aaron Courville Chapter 9 (Convolutional Networks) page 332-333)</p>

<cite style='color:blue'><kbd>strictly speaking, convolutional layers are a misnomer, since the operations they express are more accurately described as cross-correlations</kbd>. Based on our descriptions of convolutional layers, an input tensor and a kernel tensor are combined to produce an output tensor through a cross-correlation operation.</cite>

  (source: Dive into Deep Learning by Aston Zhang, Zachary C. Lipton, Mu Li, and Alexander J. Smola page 233)
  
  
-----
    

 The kernel $K$ is flipped relative to the input. If the kernel is not flipped, then convolution operation is the same as cross-correlation operation and defined as.
\begin{equation*}
S(i,j)=(I \times K)(i,j)=\sum_{m}\sum_{n}I(i+m,j+n)K(m,n)
\end{equation*}
# NOTE
<b>The input area on which a filter is applied is called local receptive field</b>
<p><b>feature maps provide a spatialized set of learned features to the subsequent layer</b></p>

## CROSS-CORRELATION OPERATIONS
<img src="../images/cross1.jpg" />
<img src="../images/cross2.jpg" />
(source: Dive into Deep Learning by Aston Zhang, Zachary C. Lipton, Mu Li, and Alexander J. Smola page 233)

## Constraining the MLP

To start off, we can consider an MLP
with two-dimensional images $\mathbf{X}$ as inputs
and their immediate hidden representations
$\mathbf{H}$ similarly represented as matrices in mathematics and as two-dimensional tensors in code, where both $\mathbf{X}$ and $\mathbf{H}$ have the same shape.
Let that sink in.
We now conceive of not only the inputs but
also the hidden representations as possessing spatial structure.

Let $[\mathbf{X}]_{i, j}$ and $[\mathbf{H}]_{i, j}$ denote the pixel
at location ($i$, $j$)
in the input image and hidden representation, respectively.
Consequently, to have each of the hidden units
receive input from each of the input pixels,
we would switch from using weight matrices
(as we did previously in MLPs)
to representing our parameters
as fourth-order weight tensors $\mathsf{W}$.
Suppose that $\mathbf{U}$ contains biases,
we could formally express the fully-connected layer as

$$\begin{aligned} \left[\mathbf{H}\right]_{i, j} &= [\mathbf{U}]_{i, j} + \sum_k \sum_l[\mathsf{W}]_{i, j, k, l}  [\mathbf{X}]_{k, l}\\ &=  [\mathbf{U}]_{i, j} +
\sum_a \sum_b [\mathsf{V}]_{i, j, a, b}  [\mathbf{X}]_{i+a, j+b}.\end{aligned},$$

where the switch from $\mathsf{W}$ to $\mathsf{V}$ is entirely cosmetic for now
since there is a one-to-one correspondence
between coefficients in both fourth-order tensors.
We simply re-index the subscripts $(k, l)$
such that $k = i+a$ and $l = j+b$.
In other words, we set $[\mathsf{V}]_{i, j, a, b} = [\mathsf{W}]_{i, j, i+a, j+b}$.
The indices $a$ and $b$ run over both positive and negative offsets,
covering the entire image.
For any given location ($i$, $j$) in the hidden representation $[\mathbf{H}]_{i, j}$,
we compute its value by summing over pixels in $x$,
centered around $(i, j)$ and weighted by $[\mathsf{V}]_{i, j, a, b}$.


(source: Dive into Deep Learning by Aston Zhang, Zachary C. Lipton, Mu Li, and Alexander J. Smola page 229-230)


## Translation Invariance
The network should respond similarly to the same patch or object, regardless of where it appears in the image. <b>This principle is called translation invariance</b>.  For example, in the classification of the handwritten digits a particular patch or object should be assigned the same classification regardless of its position within the image .


"""

Now let us invoke the first principle
established above: translation invariance.
This implies that a shift in the input $\mathbf{X}$
should simply lead to a shift in the hidden representation $\mathbf{H}$.
This is only possible if $\mathsf{V}$ and $\mathbf{U}$ do not actually depend on $(i, j)$,
i.e., we have $[\mathsf{V}]_{i, j, a, b} = [\mathbf{V}]_{a, b}$ and $\mathbf{U}$ is a constant, say $u$.
As a result, we can simplify the definition for $\mathbf{H}$:

$$[\mathbf{H}]_{i, j} = u + \sum_a\sum_b [\mathbf{V}]_{a, b}  [\mathbf{X}]_{i+a, j+b}.$$


This is a *convolution*!
We are effectively weighting pixels at $(i+a, j+b)$
in the vicinity of location $(i, j)$ with coefficients $[\mathbf{V}]_{a, b}$
to obtain the value $[\mathbf{H}]_{i, j}$.
Note that $[\mathbf{V}]_{a, b}$ needs many fewer coefficients than $[\mathsf{V}]_{i, j, a, b}$ since it
no longer depends on the location within the image.
We have made significant progress!

(source: Dive into Deep Learning by Aston Zhang, Zachary C. Lipton, Mu Li, and Alexander J. Smola page 230)
"""



In [1]:
import torch
import torch.nn.functional as F
from torch import nn
import numpy as np

In [2]:
def corr2d(X, K):
    """Compute 2D cross-correlation."""
    h,w=K.shape
    Y=torch.zeros((X.shape[0]-h+1,X.shape[1]-w+1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i,j]=(X[i:i+h,j:j+w]*K).sum()
    return Y


In [3]:
I=np.array([[0,1,2],[3,4,5],[6,7,8]])
K=np.array([[0,1],[2,3]])
I=torch.from_numpy(I)
K=torch.from_numpy(K)
#K=torch.tensor([[0,1],[2,3]])
#I=torch.tensor([[0,1,2],[3,4,5],[6,7,8]])


In [4]:
corr2d(I,K)

tensor([[19., 25.],
        [37., 43.]])

## Convolutional Layers
A convolutional layer cross-correlates the input and kernels and adds a scalar bias to produce an output.

In [5]:
class Conv2D(nn.Module):
    def __init__(self, kernel_size, **kwargs):
        super().__init__(**kwargs)
        self.w=nn.Parameter(torch.rand(kernel_size))
        self.b=nn.Parameter(torch.rand(1,))
    def forward(self,inputs):
        output=corr2d(inputs,self.w)+self.b
        return output

##  Object Edge Detection in Images

In [6]:
X = torch.ones((6, 9))
X[:, 2:6] = 0
X

tensor([[1., 1., 0., 0., 0., 0., 1., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1., 1.]])

In [7]:
K = torch.tensor([[1, -1]])
K

tensor([[ 1, -1]])

Enter X and our designed kernel K to perform the cross-correlation operations. As you can see, we
will detect 1 for the edge from white to black and -1 for the edge from black to white. The rest of
the outputs are 0

In [8]:
corr2d(X,K)

tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.,  0.]])

Let us apply the kernel to the transposed image. As expected, it vanishes. The kernel K only detects
vertical edges

In [9]:
corr2d(X.T,K)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

## Learning a Kernel



In [10]:
# Construct a convolutional layer with 1 output channel
# (channels will be introduced in the following section)
# and a kernel array shape of (1, 2)
conv2d=nn.Conv2d(in_channels=1,out_channels=1,kernel_size=(1,2),bias=False)
#conv2d=nn.Conv2d(in_channels=1,kernel_size=(1,2),out_channels=1)
# or simply
#conv2d=nn.Conv2d(1,1,kernel_size=(1,2),bias=False)

In [11]:
conv2d.parameters

<bound method Module.parameters of Conv2d(1, 1, kernel_size=(1, 2), stride=(1, 1), bias=False)>

In [12]:
conv2d.state_dict()

OrderedDict([('weight', tensor([[[[0.4192, 0.2840]]]]))])

In [13]:
Y = corr2d(X, K)

In [14]:
Y.shape

torch.Size([6, 8])

In [15]:
X = X.reshape(1, 1, 6, 9)
Y = Y.reshape(1, 1, 6, 8)

In [16]:
for i in range(10):
    Y_hat = conv2d(X)
    l = (Y_hat - Y) ** 2
    conv2d.zero_grad()
    l.mean().backward()
    # For the sake of simplicity, we ignore the bias here
    conv2d.weight.data[:] -=  3e-2  * conv2d.weight.grad
    #conv2d.bias.data[:] -= 3e-2 * conv2d.bias.grad
    if (i + 1) % 2 == 0:
        print('batch %d, loss %.3f' % (i + 1, l.sum()))

batch 2, loss 19.598
batch 4, loss 17.485
batch 6, loss 15.731
batch 8, loss 14.269
batch 10, loss 13.044


In [17]:
conv2d.weight.data.reshape(1, 2)

tensor([[0.3402, 0.0698]])

## Padding 
<img src="../images/padding.jpg" />
(source: Dive into Deep Learning by Aston Zhang, Zachary C. Lipton, Mu Li, and Alexander J. Smola page 242)

## Stride
<img src='../images/stride.jpg'>

# Multiple Input Channels

In [18]:
def corr2d_multi_in(X, K):
    # First, traverse along the 0th dimension (channel dimension) of X and K.
    # Then, add them together by using * to turn the result list into a
    # positional argument of the add_n function
    return sum(corr2d(x,k) for x,k in zip(X,K))



In [19]:
X = torch.from_numpy(np.array([[[0, 1, 2], [3, 4, 5], [6, 7, 8]],[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]))
K = torch.from_numpy(np.array([[[0, 1], [2, 3]], [[1, 2], [3, 4]]]))

In [20]:
X

tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], dtype=torch.int32)

In [21]:
corr2d_multi_in(X,K)


tensor([[ 56.,  72.],
        [104., 120.]])

# MULTIPLE OUTPUT


In [22]:
def corr2d_multi_in_out(X, K):
    # Traverse along the 0th dimension of K, and each time, perform
    # cross-correlation operations with input X. All of the results are merged
    # together using the stack function
    return np.stack([corr2d_multi_in(X, k) for k in K])

# We construct a convolution kernel with 3 output channels by concatenating the kernel array K with K+1 (plus one for each element in K) and K+2

In [23]:
K=np.stack((K,K+1,K+2))

In [24]:
corr2d_multi_in_out(X, K)

array([[[ 56.,  72.],
        [104., 120.]],

       [[ 76., 100.],
        [148., 172.]],

       [[ 96., 128.],
        [192., 224.]]], dtype=float32)

## POOLING

In [25]:
def pool2d(X, pool_size, mode='max'):
    p_h,p_w=pool_size
    Y=np.zeros((X.shape[0]-p_h+1,X.shape[1]-p_w+1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode=='max':
                Y[i,j]=torch.max((X[i:i+p_h,j:j+p_w]))
            if mode=='avg':
                Y[i,j]=torch.mean(X[i:i+p_h,j:j+p_w])
    return Y

In [26]:
X = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]],dtype=torch.float32)
pool2d(X, (2, 2))

array([[4., 5.],
       [7., 8.]])

In [27]:
pool2d(X, (2, 2),mode='avg')

array([[2., 3.],
       [5., 6.]])